use_frameworks!

# define a global platform for project
platform :ios, '9.0'

target 'Sample' do
  pod 'SlateKt', :path => '../kmp_lib'

  target 'SampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
